### ISSUE TITLE
Add data dictionary of microdata in year 1991

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/censobr#28]

**Comment by rafapereirabr** [comment]
I've started transfering the documentation to an Excel document, but this is going to take a long time (too many variables)

**Comment by jvbatista1** [comment]
Hi Rafael! I was comparing the censobr tables of **population** and **households** of 1991 with the documentation from IBGE page, but I cannot find the definitions of varibles. I know there aren't the dictionary, but do you know where can I find the description of each variable?

P.S. this pacakge is an incredible initiative, thank you so much for it!

**Comment by rafapereirabr** [comment]
Hi @jvbatista1 . Thanks for the kind message. If I remember correctly, the data dictionary is available on IBGE's ftp link.

The problem is that the data dictionary of the 1991 census is only available in a `word.doc` file. Ideally, we need these dictionary of variables to be organized in an Excel spreadsheet to create the html tables we share in censusbr. 
I've done this for the household variables, but I haven't had time to do this for the population variables. Any help here would be much appreciated.

**Comment by rafapereirabr** [comment]
this has now been implemented in the dev version and should be available on CRAN soon. Users will be able to load the dictionary of variables for the microdata of census 1991
```
 data_dictionary(year = 1991,
                 dataset = 'households',
                 showProgress = FALSE)

 data_dictionary(year = 1991,
                 dataset = 'population',
                 showProgress = FALSE)
```
