### ISSUE TITLE
Censo 2022

### ISSUE THREAD

**Issue by Suelio99** [ipeaGIT/censobr#41]
Tem alguma previsão para o censo 2022 seja incluído no pacote?

**Comment by Suelio99** [comment]
R

**Comment by rafapereirabr** [comment]
os dados do censo 2022 serão incluidos no pacote assim que o IBGE publicar os dados. A questão quando o IBGE irá publicar os dados rsrsrs . Fechando esse issue porque a questão ja esta sendo tratada no issue #9
