### ISSUE TITLE
Variáveis presente no dicionário de dados 

### ISSUE THREAD

**Issue by grettinha** [ipeaGIT/censobr#44]
Olá,

Estou utilizando o pacote censobr para carregar os dados de população do ano 2000. Notei que a variável "Sexo do último filho nascido vivo" está presente no dicionário de dados (V0464), mas não aparece nos dados efetivamente carregados. Abaixo está o código que utilizei:

```r
library(censobr)

# Carregar dados de população do ano 2000
df3 <- read_population(year = 2000,
                      showProgress = FALSE)

# Verificar se a variável está presente nos dados
colnames(df3)
```
Pode me ajudar, por favor?

**Comment by rafapereirabr** [comment]
Opa. Estou averiguando

**Comment by rafapereirabr** [comment]
acabei de ver que a importação da brase bruta nao incluiu algumas variaveis. Estou atualizando agora o script de importacao garantindo que todas colunas são lidas. Aviso aqui assim que terminar de atualizar o arquivo

**Comment by rafapereirabr** [comment]
Oi @grettinha . O arquivo foi atualizado, agora com todas variáveis. Você só precisa baixar os dados usando `cache = FALSE` uma única vez e o pacote atualiza o arquivo local no seu computador.

`df <- censobr::read_population(year = 2000, cache = FALSE)`

**Comment by grettinha** [comment]
Vou testar aqui! Muito obrigada!!

**Comment by grettinha** [comment]
@rafapereirabr, estou mexendo aqui, muita coisa de fato arrumou, mas a variável de idade, por exemplo (V4752), antes estava populada e agora está vazia.

**Comment by rafapereirabr** [comment]
Putz, vi aqui e a causa disso é uma confusão nos arquivos originais do IBGE. Essa variavel de idade em anos tem códigos diferentes nos seguintes arquivos originais:

- no arquivo SAS de leitura: `V4572` 
- no arquivo em Word de dicionario de variáveis aparecem dois codigos: `V4572` e `V4752`

Considerando que a variável correspondente de marca de imputação é `M4752`, e que o código da variável de idade calculada em meses para pessoas com menos de 1 ano é `V4754`, o correto mesmo é que o seu código seja `V4752`.

Vou corrigir isso na base

**Comment by rafapereirabr** [comment]
arquivo atualizado, @grettinha . Acho que agora está tudo certo. Veja por favor se voce encontra algum erro.

**Comment by grettinha** [comment]
Fiz alguns testes aqui e até agora está tudo perfeito! Muito obrigada, @rafapereirabr!

**Comment by rafapereirabr** [comment]
ótimo. Fechando esse issue. Se encontrar outros problemas é só avisar ! obrigado.
