### ISSUE TITLE
Problema no dicionário households

### ISSUE THREAD

**Issue by rbassidev** [ipeaGIT/censobr#45]
Estava utilizando o read_households e acabei encontrando um problema no dicionário que mudava o que eu desejava no código. 

` #Dicionário utilizado
data_dictionary(year = 2010, dataset = "households", showProgress = TRUE, cache = TRUE)

#Código utilizado

domicilio <- read_households(year = 2010,
                          columns = NULL,
                          add_labels = NULL,
                          as_data_frame = TRUE,
                          showProgress = TRUE,
                          cache = TRUE)

#sexo
domicilio2 <- select(domicilio, code_weighting, V0201, V1005) #a coluna 1005 contêm 1 - Masculino, 2 - Feminino. Deveria conter o tipo de área da moradia (urbana, rural e etc). 

nomecolunas<-c("Cod_setor","Morador_Alugado","Sexo")
colnames(domicilio2)<-nomecolunas
as.character(domicilio2$Cod_setor)
rm(domicilio2) `

**Comment by rafapereirabr** [comment]
oi @rbassidev , obrigado por abrir o issue. Sim, tem um erro de formatação na tabela que precis ser corrigido. Vou corrigir isso nos proximos dias.

enquanto isso, deixo uma dica aqui. Se voce quer trabalhar com apenas algumas colunas da base de dados, é melhor você passar as colunas que deseja para a função `read_households()`. Exemplo abaixo. Assim o processamento fica muuuito mais  rapido e leve na memoria.

```
# colunas selecionadas
cols_to_read <- c('code_weighting', 'V0201', 'V1005')

domicilio <- read_households(year = 2010,
                             columns = cols_to_read,
                             add_labels = NULL,
                             as_data_frame = TRUE,
                             showProgress = TRUE,
                             cache = TRUE)

```

**Comment by rafapereirabr** [comment]
oi @rbassidev , poblema resolvido.  O arquivo foi atualizado. Você só precisa baixar o dicionario usando `cache = FALSE` uma única vez e o pacote atualiza o arquivo local no seu computador.

`data_dictionary(year = 2010, dataset = "households", showProgress = TRUE, cache = FALSE)`
